#!/bin/bash

while true; do 
  read -p "$(whoami)@$(hostname):"$(echo -n "$PWD" | sed "s|^${HOME}|~|g")"$ " input   ;
  eval $(lua5.4 idris.lua --database=database --shell-output "${input}")               ;
done
